#pragma once

#define PP_CPP_VERSION_98_03 199711L
#define PP_CPP_VERSION_11    201103L
#define PP_CPP_VERSION_14    201402L
#define PP_CPP_VERSION_17    201703L
#define PP_CPP_VERSION_20    202002L
#define PP_CPP_VERSION_23    202302L
#define PP_CPP_VERSION_CLI   200406L

#if defined(_MSVC_LANG)
#define PP_CPP_VERSION_RAW _MSVC_LANG
#else
#define PP_CPP_VERSION_RAW __cplusplus
#endif

#if PP_CPP_VERSION_RAW == PP_CPP_VERSION_98_03
	#define PP_CPP_VERSION PP_CPP_VERSION_98_03
#elif PP_CPP_VERSION_RAW == PP_CPP_VERSION_11
	#define PP_CPP_VERSION PP_CPP_VERSION_11
#elif PP_CPP_VERSION_RAW == PP_CPP_VERSION_14
	#define PP_CPP_VERSION PP_CPP_VERSION_14
#elif PP_CPP_VERSION_RAW == PP_CPP_VERSION_17
	#define PP_CPP_VERSION PP_CPP_VERSION_17
#elif PP_CPP_VERSION_RAW == PP_CPP_VERSION_20
	#define PP_CPP_VERSION PP_CPP_VERSION_20
#elif PP_CPP_VERSION_RAW == PP_CPP_VERSION_23
	#define PP_CPP_VERSION PP_CPP_VERSION_23
#elif PP_CPP_VERSION_RAW == PP_CPP_VERSION_CLI
	#define PP_CPP_VERSION PP_CPP_VERSION_CLI
#endif
