#pragma once

#include "MouseButton.h"

namespace GLEEC
{
    enum GamepadButton : int32_t
    {
        // this is for remapping to function properly
        GAMEPAD_BUTTON_A = MOUSE_BUTTON_LAST + 1,
        GAMEPAD_BUTTON_B,
        GAMEPAD_BUTTON_X,
        GAMEPAD_BUTTON_Y,
        GAMEPAD_BUTTON_LEFT_BUMPER,
        GAMEPAD_BUTTON_RIGHT_BUMPER,
        GAMEPAD_BUTTON_BACK,
        GAMEPAD_BUTTON_START,
        GAMEPAD_BUTTON_GUIDE,
        GAMEPAD_BUTTON_LEFT_THUMB,
        GAMEPAD_BUTTON_RIGHT_THUMB,
        GAMEPAD_BUTTON_DPAD_UP,
        GAMEPAD_BUTTON_DPAD_RIGHT,
        GAMEPAD_BUTTON_DPAD_DOWN,
        GAMEPAD_BUTTON_DPAD_LEFT,
        GAMEPAD_BUTTON_LAST =   GAMEPAD_BUTTON_DPAD_LEFT,
        GAMEPAD_BUTTON_CROSS =   GAMEPAD_BUTTON_A,
        GAMEPAD_BUTTON_CIRCLE =   GAMEPAD_BUTTON_B,
        GAMEPAD_BUTTON_SQUARE =   GAMEPAD_BUTTON_X,
        GAMEPAD_BUTTON_TRIANGLE =   GAMEPAD_BUTTON_Y,
    };
}
