#pragma once

#define GRAPHICS_BACKEND_VK 1

#define GLEEC_GRAPHICS_BACKEND GRAPHICS_BACKEND_VK

#define GRAPHICS_WINDOW_BACKEND_GLFW 1

#define GLEEC_GRAPHICS_WINDOW_BACKEND GRAPHICS_WINDOW_BACKEND_GLFW
